#!/bin/bash

# Experiment 1: test whether the existing GT filtered-t+10 embedding path
# improves action prediction without visual-token generation or fusion changes.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT=${REPO_ROOT:-"$(cd "$SCRIPT_DIR/../.." && pwd)"}
cd "$REPO_ROOT"

export CONDA_ENV_NAME=${CONDA_ENV_NAME:-"vila_env_fixed"}
export MODEL_PATH=${MODEL_PATH:-"/tmp/cot_vla_eval_6_16_alltask_ckp60"}
export DATA_ROOT=${DATA_ROOT:-"/data/share/1919650160032350208/sj/LIBERO/datasets/libero_goal"}
export OUTPUT_DIR=${OUTPUT_DIR:-"./checkpoints/experiment1-oracle-subgoal-action-demo0-39-5ep"}

export DEMO_START_INDEX=${DEMO_START_INDEX:-0}
export DEMO_END_INDEX=${DEMO_END_INDEX:-40}
export ACTION_CHUNK_SIZE=${ACTION_CHUNK_SIZE:-10}
export SUBGOAL_MIN_OFFSET=${SUBGOAL_MIN_OFFSET:-10}
export SUBGOAL_MAX_OFFSET=${SUBGOAL_MAX_OFFSET:-10}
export SUBGOAL_SAMPLING_STRATEGY=${SUBGOAL_SAMPLING_STRATEGY:-fixed}

export USE_HYBRID_ATTENTION=${USE_HYBRID_ATTENTION:-True}
export USE_VISUAL_COT=${USE_VISUAL_COT:-True}
export USE_VISUAL_COT_LOSS=${USE_VISUAL_COT_LOSS:-False}
export VISUAL_LOSS_WEIGHT=${VISUAL_LOSS_WEIGHT:-0.0}
export ACTION_LOSS_WEIGHT=${ACTION_LOSS_WEIGHT:-1.0}

export XYZ_LOSS_WEIGHT=${XYZ_LOSS_WEIGHT:-1.5}
export GRIPPER_CLOSE_LOSS_WEIGHT=${GRIPPER_CLOSE_LOSS_WEIGHT:-2.0}
export GRIPPER_TRANSITION_LOSS_WEIGHT=${GRIPPER_TRANSITION_LOSS_WEIGHT:-4.0}

export TUNE_LANGUAGE_MODEL=${TUNE_LANGUAGE_MODEL:-True}
export TUNE_MM_PROJECTOR=${TUNE_MM_PROJECTOR:-True}
export TUNE_VISION_TOWER=${TUNE_VISION_TOWER:-False}
export TUNE_DEPTH_TRANSFORMER=${TUNE_DEPTH_TRANSFORMER:-False}

export LEARNING_RATE=${LEARNING_RATE:-1e-5}
export LR_SCHEDULER_TYPE=${LR_SCHEDULER_TYPE:-constant}
export WARMUP_RATIO=${WARMUP_RATIO:-0.0}
export NUM_EPOCHS=${NUM_EPOCHS:-5}

export USE_ACTION_PERCENTILE_BINS=${USE_ACTION_PERCENTILE_BINS:-True}
export REQUIRE_CHECKPOINT_ACTION_BIN_EDGES=${REQUIRE_CHECKPOINT_ACTION_BIN_EDGES:-True}

export LIGHTWEIGHT_EVAL_CHECKPOINT_EPOCHS=${LIGHTWEIGHT_EVAL_CHECKPOINT_EPOCHS:-0}
export LIGHTWEIGHT_EVAL_CHECKPOINT_EPOCH_LIST=${LIGHTWEIGHT_EVAL_CHECKPOINT_EPOCH_LIST:-1,3,5}
export SAVE_STRATEGY=${SAVE_STRATEGY:-no}
export AUTO_NEW_OUTPUT_DIR=${AUTO_NEW_OUTPUT_DIR:-False}

exec "$SCRIPT_DIR/train_action_prediction.sh" "$@"
